language: node_js
node_js:
  - 10.9.0
cache:
  directories:
    - ~/.npm
env:
  global:
    - TRUNK_BRANCH="master"
    - DEPLOY_TO="now"
before_script:
  - npm i -g npm@6.2.0
install:
  - npm ci
  - source ./ci/create-dotenv.sh
script: skip
jobs:
  include:
    - stage: test
      script:
        - npm run test:ci
    - stage: release
      if: branch = env(TRUNK_BRANCH) AND type = push
      script:
        - source ./ci/prepare-release.sh || travis_terminate 1
        - npm run release || travis_terminate 1
        - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
        - git push --follow-tags origin $TRAVIS_BRANCH || travis_terminate 1
    - stage: deploy
      if: branch = env(TRUNK_BRANCH) AND type = push AND DEPLOY_TO = 'aws'
      script:
        - CI=false npm run build
        - source ./ci/install-aws.sh || travis_terminate 1
        - aws s3 sync build/ "s3://$S3_BUCKET" --acl public-read --delete
        - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
    - stage: deploy
      if: env(DEPLOY_TO) = 'now'
      script:
        - npm install now --no-save
        - now --token NOW_TOKEN && now alias --token NOW_TOKEN
