language: node_js
node_js:
  - 10.9.0
cache:
  directories:
    - ~/.npm
env:
  global:
    - TRUNK_BRANCH="master"
before_script:
  - npm i -g npm@6.2.0
install:
  - npm ci
  - source ./ci/create-dotenv.sh
script: skip
jobs:
  include:
    - stage: test
      script:
        - npm run test:ci
      # stage for build docker container
    - stage: deploy
      # if: branch = env(TRUNK_BRANCH) AND type = push
      script:
        - CI=false npm run build
        - pip install awscli --upgrade --user
        - mkdir -p ~/.aws
        - echo '[profile eb-cli]' > ~/.aws/config
        - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/config
        - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
        - aws s3 sync build/ "s3://$S3_BUCKET" --acl public-read --delete
        # - source ./ci/deploy.sh || travis_terminate 1
    - stage: release
      if: branch = env(TRUNK_BRANCH) AND type = push
      script:
        - source ./ci/prepare-release.sh || travis_terminate 1
        - npm run release || travis_terminate 1
        - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
        - git push --follow-tags origin $TRAVIS_BRANCH || travis_terminate 1
